name: CI

on:
  push:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Push changes
        run: |
          git push -u https://${{ secrets.REPO_TOKEN }}@github.com/Grinion/qwerty-exchange-dex.git --force
